# Note that these will be implemented very progressively, so some elements may not yet be passed into the tool and serve as placeholders.
name: SS-Ti64
description: Path planning across several ternary phase diagrams from Stainless Steel (Ni9.6 Cr19.9 Fe70.5) to Ti64 (Ti0.862 Al0.102 V0.036)
nDivisionsPerDimension: 12

constraints:
  - type: equilibrium
    temperature: 900
    pressure: 1
    feasiblePhases: 
     - FCC_A1
     - BCC_A2
     - HCP_A3
  - type: LC density
    max: 11.5

elementalSpaces:
  - name: SS+V
    elements:
      - Ni
      - Cr
      - Fe
      - V
    tdb: Bobbio2021.tdb
  - name: Ti64+Cr
    elements:
      - Ti
      - Al
      - V
      - Cr
    tdb: MyTitaniumAlloys.tdb

designSpaces:

  - name: SS
    elementalSpace: SS-Cr-Ni
    components:
      - [0.096114519430,0.1993865031, 0.7044989775, 0] # SS
      - [0, 1, 0, 0] # Cr
      - [1, 0, 0, 0] # Ni
    stitch:
     - edge: 1 # opposite to SS
       targetDesignSpace: Ni-Cr-V
       targetEdge: 3 # opposite to V

  - name: Ni-Cr-V
    elementalSpace: SS+V
    components:
      - [1, 0, 0, 0] # Ni
      - [0, 1, 0, 0] # Cr
      - [0, 0, 0, 1] # V
    stitch:
      - edge: 1 # opposite to Ni
        targetDesignSpace: Ti64-Cr-V
        targetEdge: 1 # opposite to Ti64

  - name: Ti64-Cr-V
    elementalSpace: Ti64+Cr
    components:
      - [0.862, 0.102, 0.036, 0] # Ti64
      - [0, 0, 1, 0] # V
      - [0, 0, 0, 1] # Cr

pathPlan:
  - designSpace: SS
    position: [12, 0, 0]
  - designSpace: Ti64-Cr-V
    index: -1 # Last position in the design space corresponding to 100% of the first component
  